import { Card } from "./Interfaces";

export const deck: Array<Card> = [
  { id: 1, name: "2", naipe: "copas", value: 0, order: 0 },
  { id: 2, name: "3", naipe: "copas", value: 0, order: 1 },
  { id: 3, name: "4", naipe: "copas", value: 0, order: 2 },
  { id: 4, name: "5", naipe: "copas", value: 0, order: 3 },
  { id: 5, name: "6", naipe: "copas", value: 0, order: 4 },
  { id: 6, name: "dama", naipe: "copas", value: 2, order: 5 },
  { id: 7, name: "valete", naipe: "copas", value: 3, order: 6 },
  { id: 8, name: "rei", naipe: "copas", value: 4, order: 7 },
  { id: 9, name: "7", naipe: "copas", value: 10, order: 8 },
  { id: 10, name: "as", naipe: "copas", value: 11, order: 9 },

  { id: 11, name: "2", naipe: "paus", value: 0, order: 0 },
  { id: 12, name: "3", naipe: "paus", value: 0, order: 1 },
  { id: 13, name: "4", naipe: "paus", value: 0, order: 2 },
  { id: 14, name: "5", naipe: "paus", value: 0, order: 3 },
  { id: 15, name: "6", naipe: "paus", value: 0, order: 4 },
  { id: 16, name: "dama", naipe: "paus", value: 2, order: 5 },
  { id: 17, name: "valete", naipe: "paus", value: 3, order: 6 },
  { id: 18, name: "rei", naipe: "paus", value: 4, order: 7 },
  { id: 19, name: "7", naipe: "paus", value: 10, order: 8 },
  { id: 20, name: "as", naipe: "paus", value: 11, order: 9 },

  { id: 21, name: "2", naipe: "ouros", value: 0, order: 0 },
  { id: 22, name: "3", naipe: "ouros", value: 0, order: 1 },
  { id: 23, name: "4", naipe: "ouros", value: 0, order: 2 },
  { id: 24, name: "5", naipe: "ouros", value: 0, order: 3 },
  { id: 25, name: "6", naipe: "ouros", value: 0, order: 4 },
  { id: 26, name: "dama", naipe: "ouros", value: 2, order: 5 },
  { id: 27, name: "valete", naipe: "ouros", value: 3, order: 6 },
  { id: 28, name: "rei", naipe: "ouros", value: 4, order: 7 },
  { id: 29, name: "7", naipe: "ouros", value: 10, order: 8 },
  { id: 30, name: "as", naipe: "ouros", value: 11, order: 9 },

  { id: 31, name: "2", naipe: "espadas", value: 0, order: 0 },
  { id: 32, name: "3", naipe: "espadas", value: 0, order: 1 },
  { id: 33, name: "4", naipe: "espadas", value: 0, order: 2 },
  { id: 34, name: "5", naipe: "espadas", value: 0, order: 3 },
  { id: 35, name: "6", naipe: "espadas", value: 0, order: 4 },
  { id: 36, name: "dama", naipe: "espadas", value: 2, order: 5 },
  { id: 37, name: "valete", naipe: "espadas", value: 3, order: 6 },
  { id: 38, name: "rei", naipe: "espadas", value: 4, order: 7 },
  { id: 39, name: "7", naipe: "espadas", value: 10, order: 8 },
  { id: 40, name: "as", naipe: "espadas", value: 11, order: 9 }
];